version: "3.9"

services:

  postgis:
    image: postgis/postgis:16-3.4
    container_name: geodata_postgis
    environment:
      POSTGRES_DB: geodata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
